#!/bin/bash

set -e

H_DEST=../../data_header
C_DEST=../../data_source
IMG_SOURCE=../../graphics_raw

if [ ! -d "./tmpDir" ]; then
    mkdir "tmpDir"
fi

NAME=$(basename $1)
NAME="${NAME%.*}"
IFS='-'
read -ra ADDR <<< "$NAME"
base_name="${ADDR[0]}"
bit_depth="${ADDR[1]}"
do_split="${ADDR[2]}"
hsplit="${ADDR[3]}"
vsplit="${ADDR[4]}"

echo $base_name $bit_depth $do_split $hsplit $vsplit
./bmp4c "$1" tmpDir/"$base_name".c "$bit_depth" "$do_split" "$hsplit" "$vsplit"

mv tmpDir/"$base_name".c "$C_DEST"/"$base_name".c
mv tmpDir/"$base_name".h "$H_DEST"/"$base_name".h
